name: GitHub Pages

on:
  push:
    branches: ["main"]

# 权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -e .
        pip install -e .[docs]

    - name: Build Sphinx documentation
      run: |
        cd docs && make html && touch build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/build/html
